import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FaInstagram, FaPhone } from "react-icons/fa";
import { MdEmail } from 'react-icons/md';
import { FaLinkedin } from 'react-icons/fa';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <header>
            <nav>
              <div className="nav"><Link className="hover:text-orange-500 duration-300" href="/">Home</Link> | <Link className="hover:text-orange-500 duration-300" href="/about">About Me</Link> | <Link className="hover:text-orange-500 duration-300" href="/projects">Projects</Link> | <Link className="hover:text-orange-500 duration-300" href="/contact">Contact</Link></div>

            </nav>
          </header>
          <main className="mb-24">{children}</main>
          <footer className="mt-24">
            © 2024 Yohannes Fikre
            <h2>Yohannes Fikre</h2>
            <div className="flex justify-center mt-6">
              <div className="flex gap-16 mx-auto">
                <Link className="text-2xl hover:text-orange-500 duration-300" href="tel:+125986589983">
                  <FaPhone />
                </Link>

                <Link className="text-2xl hover:text-orange-500 duration-300" href="mailto:yohannesjho12@gmail.com">
                  <MdEmail />
                </Link>

                <Link className="text-2xl hover:text-orange-500 duration-300" href="https://www.linkedin.com/in/yohannes-fikre-104703234/">
                  <FaLinkedin />
                </Link>

                <Link className="text-2xl hover:text-orange-500 duration-300" href="https://www.instagram.com/johnianso/">
                  <FaInstagram />
                </Link>

              </div>
            </div>

          </footer>
        </div>

      </body>
    </html>
  );
}
